import { TeacherCardConfig } from '@/types/registry';

export const TEACHERS_V1: TeacherCardConfig[] = [
  { id: "herr-zeiler", name: "Herr Zeiler", rarity: "legendary", type: "teacher", hp: 145, description: "Macht gerne früher Schluss.", attacks: [{"damage":25,"name":"TÜRKEI BESUCH","description":"FÜR DIE HAIRLINE"},{"description":"Mag er halt","name":"Vogel Biss","damage":10},{"description":"Lethal ","name":"„Och Finn“","damage":20}] },
  { id: "frau-bennari", name: "Frau Bennari", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Klausur korrigieren", damage: 15 }] },
  { id: "frau-biastoch", name: "Frau Biastoch", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Hefterkontrolle", damage: 20 }] },
  { id: "frau-bien", name: "Frau Bien", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Summ-Attacke", damage: 15 }] },
  { id: "frau-bley", name: "Frau Bley", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Vokabeltest", damage: 15 }] },
  { id: "frau-burckhardt", name: "Frau Burckhardt", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Analyse", damage: 20 }] },
  { id: "frau-clemens", name: "Frau Clemens", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Lesestunde", damage: 15 }] },
  { id: "frau-courant-fernandes", name: "Frau Courant Fernandes", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Vokabel-Sprint", damage: 15 }] },
  { id: "frau-deleske", name: "Frau Deleske", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Zuhören!", damage: 15 }] },
  { id: "frau-drescher", name: "Frau Drescher", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Diktat", damage: 15 }] },
  { id: "frau-ernst", name: "Frau Ernst", rarity: "rare", type: "teacher", hp: 110, description: "Zu Verhaltensstreng", attacks: [{"name":"Sozialberater","damage":15},{"description":"Eigentlich Lustig","name":"Belehrung an die Jungs","damage":10}] },
  { id: "frau-feuerbach", name: "Frau Feuerbach", rarity: "epic", type: "teacher", hp: 125, description: "Besitzerin des Kunst Raumes", attacks: [{"name":"Leporello ","damage":15,"description":"Zu viel Arbeit"},{"damage":20,"name":"70% Motivation","description":"Note trotzdem gewürfelt"}] },
  { id: "frau-fiedler", name: "Frau Fiedler", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Formel-Check", damage: 20 }] },
  { id: "frau-franke", name: "Frau Franke", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Grammatik-Hammer", damage: 20 }] },
  { id: "frau-friedrich", name: "Frau Friedrich", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Experiment", damage: 20 }] },
  { id: "frau-fritzsch", name: "Frau Fritzsch", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Notiz machen", damage: 15 }] },
  { id: "frau-galle", name: "Frau Galle", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Quellenkritik", damage: 20 }] },
  { id: "frau-gantumur", name: "Frau Gantumur", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Vokabeln!", damage: 15 }] },
  { id: "frau-ganzer", name: "Frau Ganzer", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Hausaufgaben-Check", damage: 20 }] },
  { id: "frau-haase", name: "Frau Haase", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Häschen-Hüpfer", damage: 15 }] },
  { id: "frau-henker", name: "Frau Henker", rarity: "epic", type: "teacher", hp: 125, attacks: [{ name: "Urteilsspruch", damage: 30 }] },
  { id: "frau-hoppe", name: "Frau Hoppe", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Hopp-Hopp", damage: 15 }] },
  { id: "frau-jerol", name: "Frau Jerol", rarity: "common", type: "teacher", hp: 95, description: "", attacks: [{"damage":10,"name":"FEMINISTEN ATTACKE","description":"HALT NUR WÜTEND"},{"damage":5,"name":"STANLEY ATTACKE "}] },
  { id: "frau-jurk", name: "Frau Jurk", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Mitschrift", damage: 15 }] },
  { id: "frau-k-gler", name: "Frau Kügler", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Lernkontrolle", damage: 15 }] },
  { id: "frau-k-nzelmann", name: "Frau Künzelmann", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Vortrag", damage: 15 }] },
  { id: "frau-kaule", name: "Frau Kaule", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Kausalkette", damage: 15 }] },
  { id: "frau-kober", name: "Frau Kober", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Kurzvortrag", damage: 15 }] },
  { id: "frau-kobisch", name: "Frau Kobisch", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Karte ziehen", damage: 15 }] },
  { id: "frau-krenzke", name: "Frau Krenzke", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Kartenarbeit", damage: 15 }] },
  { id: "frau-laber", name: "Frau Laber", rarity: "epic", type: "teacher", hp: 125, attacks: [{ name: "Dauerreden", damage: 30 }] },
  { id: "frau-link", name: "Frau Link", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Verknüpfung", damage: 15 }] },
  { id: "frau-loitsch", name: "Frau Loitsch", rarity: "mythic", type: "teacher", hp: 135, description: "Sehr Netten Mann", attacks: [{ name: "Physik-Rätsel", damage: 40 }] },
  { id: "frau-manuwald", name: "Frau Manuwald", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Schreibübung", damage: 15 }] },
  { id: "frau-matz", name: "Frau Matz", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Mathe-Trick", damage: 20 }] },
  { id: "frau-meinhold", name: "Frau Meinhold", rarity: "mythic", type: "teacher", hp: 135, description: "Mag irgendwie keiner", attacks: [{"description":"Fatal","name":"„Sie“","damage":30},{"description":"Gar kein Bock","damage":15,"name":"Stundenarbeit"}] },
  { id: "frau-mey", name: "Frau Mey", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Maiglöckchen", damage: 15 }] },
  { id: "frau-neufeldt", name: "Frau Neufeldt", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Neuland", damage: 20 }] },
  { id: "frau-neugebauer", name: "Frau Neugebauer", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Grundstein", damage: 15 }] },
  { id: "frau-nims", name: "Frau Nims", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Nimm's leicht", damage: 15 }] },
  { id: "frau-nobis", name: "Frau Nobis", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Edelmütig", damage: 15 }] },
  { id: "frau-packheiser", name: "Frau Packheiser", rarity: "common", type: "teacher", hp: 105, description: "Bio Gk", attacks: [{"name":"Enzyme Malen","damage":10},{"damage":15,"name":"Mikroskopieren "}] },
  { id: "frau-peucker", name: "Frau Peucker", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Paukenschlag", damage: 15 }] },
  { id: "frau-piwonka", name: "Frau Piwonka", rarity: "epic", type: "teacher", hp: 125, description: "Zu Komplexe Aufgaben", attacks: [{"name":"Eisenhelm werfen","damage":25,"description":"Tut schon weh"},{"description":"Kommandantin ","name":"BigBand Armee","damage":15}] },
  { id: "frau-r-hling", name: "Frau Röhling", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Rollenverteilung", damage: 15 }] },
  { id: "frau-r-mer", name: "Frau Römer", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Latein-Power", damage: 25 }] },
  { id: "frau-reichelt", name: "Frau Reichelt", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Reichtum an Wissen", damage: 15 }] },
  { id: "frau-rosenthal", name: "Frau Rosenthal", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Rosen-Dorn", damage: 15 }] },
  { id: "frau-runge", name: "Frau Runge", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Langstreckenlauf", damage: 15 }] },
  { id: "frau-ruscher", name: "Frau Ruscher", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Schnelligkeit", damage: 20 }] },
  { id: "frau-schier", name: "Frau Schier", rarity: "rare", type: "teacher", hp: 110, description: "ICH HAB DAS FEUER GELÖSCHT", attacks: [{"name":"FEUER LÖSCHEN","damage":25},{"name":"RAUCH SEHEN","damage":10}] },
  { id: "frau-schimek", name: "Frau Schimek", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Schachzug", damage: 20 }] },
  { id: "frau-schmidt", name: "Frau Schmidt", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Standard-Check", damage: 15 }] },
  { id: "frau-schultz", name: "Frau Schultz", rarity: "rare", type: "teacher", hp: 110, description: "Nette Mathelehrerin", attacks: [{"description":"Lk Easy","damage":15,"name":"Dreieck Berechnen"},{"description":"-Aura","damage":25,"name":"Falsche Lösung anschreiben"}] },
  { id: "frau-schumann", name: "Frau Schumann", rarity: "epic", type: "teacher", hp: 125, description: "Sehr Nette Lehrerin", attacks: [{"description":"Gehörschutz Empfohlen ","name":"Grelle Stimme","damage":25},{"description":"Bringt halt nichts","damage":10,"name":"Willhelm ein Helm geben"}] },
  { id: "frau-schwarzer", name: "Frau Schwarzer", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Schwarzmalerei", damage: 15 }] },
  { id: "frau-stein", name: "Frau Stein", rarity: "common", type: "teacher", hp: 100, attacks: [{ name: "Stein-Wurf", damage: 15 }] },
  { id: "frau-stelzig", name: "Frau Stelzig", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Stelzen-Lauf", damage: 15 }] },
  { id: "frau-strote", name: "Frau Strote", rarity: "epic", type: "teacher", hp: 125, attacks: [{ name: "Strenge", damage: 30 }] },
  { id: "frau-t-th", name: "Frau Tóth", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Ungarn-Power", damage: 20 }] },
  { id: "frau-unger", name: "Frau Unger", rarity: "mythic", type: "teacher", hp: 135, description: "", attacks: [{"name":"Schwarze Klamotten ","damage":20,"description":"Endgegner Drip"},{"description":"Demotiviereung Nr. 1 ","damage":25,"name":"1vs1 Klausurausgabe"}] },
  { id: "frau-vogel", name: "Frau Vogel", rarity: "mythic", type: "teacher", hp: 135, attacks: [{ name: "Vogel-Flug", damage: 35 }] },
  { id: "frau-wahl", name: "Frau Wahl", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Wahl-Kampf", damage: 15 }] },
  { id: "frau-weise", name: "Frau Weise", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Weisheit", damage: 25 }] },
  { id: "frau-wendorff", name: "Frau Wendorff", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Diplomatie", damage: 20 }] },
  { id: "frau-wilke", name: "Frau Wilke", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Willenskraft", damage: 15 }] },
  { id: "frau-wonneberger", name: "Frau Wonneberger", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Wonne-Gefühl", damage: 15 }] },
  { id: "herr-altenhenne", name: "Herr Altenhenne", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Altersschlag", damage: 20 }] },
  { id: "herr-de-vivanco", name: "Herr de Vivanco", rarity: "epic", type: "teacher", hp: 125, description: "WIR MACHEN HEUTE SCHÜLERVERSUCHE", attacks: [{"name":"GROßER LEIM","damage":20,"description":"KLEBRIG"},{"name":"HÜBSCHE HOSE","damage":15}] },
  { id: "herr-fritzsch", name: "Herr Fritzsch", rarity: "common", type: "teacher", hp: 95, attacks: [{ name: "Frischling", damage: 15 }] },
  { id: "herr-fuchs", name: "Herr Fuchs", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Fuchs-List", damage: 20 }] },
  { id: "herr-gr-ler", name: "Herr Gräßler", rarity: "legendary", type: "teacher", hp: 145, description: "Dem muss in Sommer doch warm sein", attacks: [{"name":"Klingelton","damage":15,"description":"Das A-Team kommt"},{"description":"","name":"2 Wochen Afghanistan EINSATZ","damage":30}] },
  { id: "herr-grabowski", name: "Herr Grabowski", rarity: "epic", type: "teacher", hp: 125, attacks: [{ name: "Grabung", damage: 25 }] },
  { id: "herr-j-rg", name: "Herr Jörg", rarity: "rare", type: "teacher", hp: 110, description: "Latein Nr. 1", attacks: [{"description":"Fatal","name":"Mika und Oli hassen","damage":25},{"description":"Check nix","damage":15,"name":"Gottlose Viele Aufgaben machen"}] },
  { id: "herr-k-nner", name: "Herr Känner", rarity: "iconic", type: "teacher", hp: 160, description: "Ober Boss", attacks: [{"name":"Elterngespräch ","damage":25,"description":"Och nö "},{"damage":50,"name":"Verweis","description":"Ab nach Hause"}] },
  { id: "herr-kaiser", name: "Herr Kaiser", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Kaiserschnitt", damage: 25 }] },
  { id: "herr-kreye", name: "Herr Kreye", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Kreativität", damage: 20 }] },
  { id: "herr-kutschick", name: "Herr Kutschick", rarity: "epic", type: "teacher", hp: 125, attacks: [{ name: "Kutschen-Fahrt", damage: 30 }] },
  { id: "herr-lange", name: "Herr Lange", rarity: "common", type: "teacher", hp: 100, attacks: [{ name: "Langer Atem", damage: 15 }] },
  { id: "herr-loitsch", name: "Herr Loitsch", rarity: "legendary", type: "teacher", hp: 145, description: "Alt aber immernoch Top-Fit", attacks: [{"damage":40,"name":"Physik Gott","description":"Machste nix"},{"description":"Schlimmer als Latein","damage":20,"name":"Mathe Sprache üben"}] },
  { id: "herr-lory", name: "Herr Lory", rarity: "mythic", type: "teacher", hp: 135, description: "Kann man gut mit Reden", attacks: [{"description":"Siehste Nix","name":"Schiel-Attacke ","damage":20},{"name":"Lautstärke x2","damage":15,"description":"Gehörsturz"}] },
  { id: "herr-moch", name: "Herr Moch", rarity: "epic", type: "teacher", hp: 125, description: "DU BIST EIN NICHTS", attacks: [{"name":"Abwertend manchen Menschgruppen  gegenüber","damage":30,"description":"Schon Bodenlos"},{"damage":20,"name":"Haasen gegen die Wand werfen "}] },
  { id: "herr-musiol", name: "Herr Musiol", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Musik-Stunde", damage: 20 }] },
  { id: "herr-rehnolt", name: "Herr Rehnolt", rarity: "epic", type: "teacher", hp: 125, attacks: [{ name: "Regelung", damage: 30 }] },
  { id: "herr-rentsch", name: "Herr Rentsch", rarity: "mythic", type: "teacher", hp: 135, description: "JETZT IST UNTERRICHT JETZT BIN ICH GEIL", attacks: [{"description":"Alle Instrumente können","name":"Solo Orchester ","damage":25},{"description":"PAYFONE","damage":15,"name":"FASCHING SAVEN"}] },
  { id: "herr-richter", name: "Herr Richter", rarity: "legendary", type: "teacher", hp: 145, description: "Bester Lehrer der Schule", attacks: [{"description":"Süßer Typ","damage":5,"name":"Eis essen"},{"description":"High Definition Multimedia Interface","name":"Technik Probleme","damage":50}] },
  { id: "herr-riedel", name: "Herr Riedel", rarity: "legendary", type: "teacher", hp: 145, description: "Fahrrad Fanatiker", attacks: [{"description":"Ganz Interessant ","name":"Familien Geschichten ","damage":15},{"name":"Klausur nach 2 Jahren nichts tun","damage":40,"description":"Endgame"}] },
  { id: "herr-ritter", name: "Herr Ritter", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Ritterschlag", damage: 25 }] },
  { id: "herr-sarodnik", name: "Herr Sarodnik", rarity: "mythic", type: "teacher", hp: 135, description: "Flexer Nr. 1 (aber garnich so Krass)", attacks: [{"name":"BMW Rev","damage":10,"description":"Halt geleased"},{"name":"1vs1 Clash Royale","damage":40,"description":"Halt Top 100"}] },
  { id: "herr-schlegel", name: "Herr Schlegel", rarity: "epic", type: "teacher", hp: 125, description: "", attacks: [{"name":"FREAKY FRIDAY","damage":30,"description":"OH YEAH"},{"damage":15,"name":"FAHRRAD FAHREN ","description":"AB GEHTS"}] },
  { id: "herr-schneider", name: "Herr Schneider", rarity: "epic", type: "teacher", hp: 125, attacks: [{ name: "Zuschnitt", damage: 25 }] },
  { id: "herr-scholz", name: "Herr Scholz", rarity: "epic", type: "teacher", hp: 125, description: "Halber Schüler noch", attacks: [{"damage":25,"name":"Mac Book Attacke","description":"Aluminium Tut schon weh"},{"damage":15,"name":"Lehrbuch Aufgaben"}] },
  { id: "herr-schulze", name: "Herr Schulze", rarity: "rare", type: "teacher", hp: 115, description: "WIKINGER", attacks: [{"damage":25,"name":"BONSAI ZÜCHTEN "}] },
  { id: "herr-stange", name: "Herr Stange", rarity: "mythic", type: "teacher", hp: 150, description: "Abstand halten und Mitschrieben", attacks: [{"description":"Kann er aber nich","damage":25,"name":"Anschreien "},{"damage":35,"name":"Hefter Raus!"}] },
  { id: "herr-stange-junior-1774192999093", name: "Herr Stange Junior", rarity: "rare", type: "teacher", hp: 130, description: "", attacks: [{"description":"100kg ","name":"Bankdrücken","damage":30},{"damage":15,"name":"Bodenturnen "}] },
  { id: "herr-stirner", name: "Herr Stirner", rarity: "epic", type: "teacher", hp: 125, description: "", attacks: [{"damage":30,"name":"Hantel Werfen"}] },
  { id: "herr-stuhlmacher", name: "Herr Stuhlmacher", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Handarbeit", damage: 20 }] },
  { id: "herr-trinczek", name: "Herr Trinczek", rarity: "mythic", type: "teacher", hp: 135, description: "Technik Gott", attacks: [{"description":"Ist halt OP","damage":45,"name":"Server Lahmlegen "},{"name":"Basecap Wurf ","damage":15,"description":"Tut schon weh"}] },
  { id: "herr-wei-", name: "Herr Weiß", rarity: "mythic", type: "teacher", hp: 135, description: "Business Meister", attacks: [{"name":"90 Vorlesung","damage":20,"description":"Einschläfernd "},{"description":"Viel zu viel","damage":30,"name":"680 Seiten VW Analysieren"}] },
  { id: "frau-richter", name: "Frau Richter", rarity: "iconic", type: "teacher", hp: 160, description: "Old but Gold", attacks: [{"description":"Oh nein ","name":"In Rente Gehen ","damage":60},{"damage":20,"name":"Kunstausstellung  ","description":"Sehr schöne Bilder"}] },
  { id: "frau-kmpf", name: "Frau Kämpf", rarity: "rare", type: "teacher", hp: 110, attacks: [{ name: "Kampfgeist", damage: 25 }] }
];
